# Page settings
baseurl = "localhost:1313"
title = "HTECH Consulting | Brisbane"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "jessica.hart"
  description = ""
  email = "info@htechconsulting.com.au"

  # Navigation
  [params.navigation]
    logo = "full_logo_white_trans.png"
    home = "Home"
    services = "Services"
    contact = "Contact"
  
  # Hero section
  [params.hero]
    title = "HTECH Consulting"
    subtitle = 'Brisbane Cloud Consulting Services'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Analyse"
    description = "Our solution specialists will analyse your business processes to identify areas for improvement."
    url = "#"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "With a focus on Microsoft technologies, a solution will be created to streamline your business process."
    url = "#"
    button = "Get In Touch"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Implement"
    description = "Our team will work with with you to deploy your new solution with the least amount of friction possible.  "
    url = "#"
    button = "Get In Touch"
    icon = "icon-rocket"
    img = "img_10.jpg"

  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "HTECH Consulting uses a Microsoft centric approach to solution design. "

    [[params.services.item]]
      title = "Azure"
      description = "Microsoft Azure is our public cloud of choice and integrates seamlessly with other Microsoft 365 solutions. Azure is an industry leader in public cloud offerings."
      icon = "icon-screen-desktop"

    [[params.services.item]]
      title = "Microsoft 365 Power Platform"
      description = "The Power Platform is a modern approach to application design, providing an excellent toolset for business transformation within the Microsoft ecosystem."
      icon = "icon-layers2"
    
      [[params.services.item]]
      title = "Security"
      description = "Security is often overlooked in Small and Medium sized business. We will ensure a strict set of security standards is applied to any solutions we provide."
      icon = "icon-lock"

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = "Contact us for your service needs"
    
  # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Brisbane"],
        ["icon-envelope", "info@htechconsulting.com.au"],
        ["icon-globe", '<a href="www.htechconsulting.com.au" target="_blank">www.htechconsulting.com.au</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = 'HTECH Consulting'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
